### ISSUE TITLE
Add License to Repository

### ISSUE THREAD

**Issue by chznbaum** [757colorcoded/wp-colorcoded#2]
This child theme should have an open source license applied. Following the [instructions GitHub provides](https://help.github.com/articles/adding-a-license-to-a-repository/), the GPL-3 license should be added to the repository.

Please make this change in a separate branch or in a personal fork of the repository, and then create a Pull Request.

**Comment by dillionverma** [comment]
Ill take this

**Comment by chznbaum** [comment]
Resolved by #5
